name: test_lib2
description: A starting point for Dart libraries or applications.
version: 1.2.0
# homepage: https://www.example.com
# author: dis <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  code_health_meta:
     path: ../../code_health_meta
